name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          profile: minimal
          override: true
    - name: Install wasm toolchain
      run: rustup target add wasm32-unknown-unknown
    - name: Install wasm-bindgen
      run: cargo install -f wasm-bindgen-cli
    - name: Build 3dmot
      run: cargo build --example 3d_mot --target wasm32-unknown-unknown --release
    - name: Bind outputs
      run: wasm-bindgen --out-dir pages target/wasm32-unknown-unknown/release/examples/3d_mot.wasm --target web
    - name: Build 2dmot
      run: cargo build --example 2d_mot --target wasm32-unknown-unknown --release
    - name: Bind outputs
      run: wasm-bindgen --out-dir pages target/wasm32-unknown-unknown/release/examples/2d_mot.wasm --target web
    - name: Build AION source
      run: cargo build --example aion_source --target wasm32-unknown-unknown --release
    - name: Bind outputs
      run: wasm-bindgen --out-dir pages target/wasm32-unknown-unknown/release/examples/aion_source.wasm --target web
    - name: Build TOP trap
      run: cargo build --example top_trap --target wasm32-unknown-unknown --release
    - name: Bind outputs
      run: wasm-bindgen --out-dir pages target/wasm32-unknown-unknown/release/examples/top_trap.wasm --target web
    - name: Copy assets directory
      run: cp assets pages -R
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: deploy
        folder: pages